### ISSUE TITLE
[Mohist 1.12.2] HeadLibrary prints errors when executing /heads 

### ISSUE THREAD

**Issue by Agrrox** [Tigahz/HeadLibrary#4]
HeadLibrary seems to be enabled but the plugin prints error message upon using /heads command.

## Server Setup:

Mohist version: 1.12.2 build #192
<details>
<summary>Plugins:</summary>

```
AdvancedBan (v2.3.0)
AnnouncerPlus (v1.2.3)
BKCommonLib (v1.16.5-v3-SNAPSHOT)
BannerMaker (v1.9.0)
BannerText (v1.12.2-1)
BetterBrushes (v1.0.0.140406)
CommandSigns (v1.6.7)
HeadLibrary (v5.2.1)
DeluxeMenus (v1.13.3-Release)
Essentials (v2.18.2.0)
EssentialsSpawn (v2.18.2.0)
F3NPerm (v2.5)
HolographicExtension (v1.10.9)
ItemJoin (v5.2.1-RELEASE-b678)
LastLoginAPI (v1.4.3)
LightCleaner (v1.16.5-v1)
LuckPerms (v5.2.76)
PlaceholderAPI (v2.10.9)
ProtocolLib (v4.5.1)
RelativeCoordCalculator (v0.5)
SchematicBrush (v0.5.2-20)
Sledgehammer (v0.4.2)
TabTPS (v1.3.3)
TouchscreenHolograms (v1.4.2)
Vault (v1.6.7-b${env.TRAVIS_BUILD_NUMBER})
VentureChat (v2.21.1)
VoxelSniper (v5.171.0-CC_COMPAT-SNAPSHOT)
WorldEdit (v6.1.9;caf0ad9)
WorldGuard (v6.2.2-SNAPSHOT;8eeab68)
WorldGuardExtraFlags (v4.1.4)
```
</details>
<details>
<summary>Mods:</summary>

```
Aroma1997Core-1.12.2-2.0.0.2.b167
AromaBackup-1.12.2-3.0.0.0.b135
CubicChunks-1.12.2-0.0.1185.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.145.0-SNAPSHOT-all
bannermod-1.1.0
ccpregen-0.0.21
morecompressions-3.0.0.0.b135
rhino-1.7.12
terra121-0.1.5.1.
terramap-1.0.0-beta6.6
worldedit-forge-mc1.12.2-6.1.11-cubicchunks-SNAPSHOT-dist

```

</details>

## Error Messages:
<details>
<summary>enabling messages:</summary>

```powershell
[02:27:12] [Server thread/INFO] [Mohist]: Enabling HeadLibrary v5.2.1
[02:27:12] [Server thread/INFO] [Mohist]: [HeadLibrary] Head Database loaded
[02:27:12] [Server thread/INFO] [Mohist]: [HeadLibrary] Letter Database loaded
[02:27:12] [Server thread/INFO] [Mohist]: [HeadLibrary] Custom Head Database loaded
[02:27:12] [Server thread/INFO] [Mohist]: [HeadLibrary] Metrics Enabled!
[02:27:12] [Server thread/INFO] [Mohist]: Enabling Essentials v2.18.2.0

```

</details>
<details>
<summary>error message when using commands:</summary>

```powershell
[02:28:36 INFO]: Agrro issued server command: /heads
[02:28:36 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'heads' in plugin HeadLibrary v5.2.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchFieldError: PLAYER_HEAD
        at me.tigahz.headlibrary.builders.HeadBuilder.<init>(HeadBuilder.java:26) ~[?:?]
        at me.tigahz.headlibrary.gui.CategoryGUI.getInventory(CategoryGUI.java:48) ~[?:?]
        at me.tigahz.headlibrary.gui.CategoryGUI.openMenu(CategoryGUI.java:70) ~[?:?]
        at me.tigahz.headlibrary.commands.CommandManager.onCommand(CommandManager.java:103) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more
```
</details>
<details>
<summary>plugin does reload, but same error message when using command:</summary>

```powershell
[03:42:11 INFO]: Agrro issued server command: /heads reload
[03:42:11 INFO]: [HeadLibrary] Head Database loaded
[03:42:12 INFO]: [HeadLibrary] Letter Database loaded
[03:42:12 INFO]: [HeadLibrary] Custom Head Database loaded
[03:42:15 INFO]: Agrro issued server command: /heads
[03:42:15 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'heads' in plugin HeadLibrary v5.2.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchFieldError: PLAYER_HEAD
        at me.tigahz.headlibrary.builders.HeadBuilder.<init>(HeadBuilder.java:26) ~[?:?]
        at me.tigahz.headlibrary.gui.CategoryGUI.getInventory(CategoryGUI.java:48) ~[?:?]
        at me.tigahz.headlibrary.gui.CategoryGUI.openMenu(CategoryGUI.java:70) ~[?:?]
        at me.tigahz.headlibrary.commands.CommandManager.onCommand(CommandManager.java:103) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more```

</details>

unfortunately logs are useless on Mohist

**Comment by Tigahz** [comment]
Hi, 
For 1.13, Mojang changed the way materials work. As the plugin is coded toward 1.13 and above, you would have to those versions for the plugin to work.
